# Billettpriser og rabatter

**Læringsmål:**

* Betingelser

I denne oppgaven skal du bruke betingelser (if-elif-else) til å bestemme billettprisen til en bruker basert på input fra brukeren. 

Transportselskapet «TravelevatoR» tilbyr reiser fra Trondheim til Pythonville. Ved bestilling minst 14 dager før man skal reise, kan man få minipris 199. Normal billett koster 440. 

## Oppgave a: frivillig

Skriv en funskjon med to mulige oppførsler som vist under:

  
```python
>>>billettpris(15)
  
Du kan få minipris: 199,-  
```

```python
>>>billettpris(10)

Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-  
```
***Skriv koden din under***

In [5]:
def bilettpris(tall):
    if tall == 15:
        return print("Du kan få minipris: 199,-")
    elif tall == 10:
        return print("Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-")
    
bilettpris(10)
bilettpris(15)


Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-
Du kan få minipris: 199,-


## Oppgave b: frivillig

Det hender av og til at kunder ikke ønsker minipris, men heller vil ha fullprisbillett. Dette fordi minipris ikke kan refunderes / endres. Utvid derfor funksjonen så kunder kan legge til informasjon om de ønsker minipris – men kun der det er relevant. To eksempel på kjøring etter utvidelsen:

  
```python
>>>billetpris(15, 'J')

Du kan få minipris og ønsker dette, billettpris: 199,-
```
  
```python
>>>billetpris(15, 'N')

Du kan få minipris, men ønsker ikke det. Da tilbyr vi fullpris: 440,-
```

***Skriv koden din under***

In [7]:
def bilettpris(tall, valg):
    if tall == 15 and valg == "J":
        return print("Du kan få minipris: 199,-")
    elif tall == 15 and valg == "N":
         return print("Du kan få minipris, men ønsker ikke det. Da tilbyr vi fullpris: 440,-")
    elif tall == 10:
        return print("Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-")
    
bilettpris(10, "J")
bilettpris(15, "J")
bilettpris(15, "N")


Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-
Du kan få minipris: 199,-
Du kan få minipris, men ønsker ikke det. Da tilbyr vi fullpris: 440,-


## Oppgave c: frivillig

Det blir besluttet at barn under 16 gis 50% rabatt. Senior (60+), militær i uniform, og student gis 25% rabatt. Om man f.eks. både er 60+ og militær / student, får man likevel bare 25% rabatt. Alle disse rabattene gjelder kun i forhold til fullpris, for minipris gis ingen rabatter. Endre funksjonen så kunder må gi informasjon om alder, evt. også om student / militær, og regner ut riktig pris.

Eksempel på kjøring av koden:

  
```python
>>>billettpris(15, 'J', 'militær')

Du kan få minipris og ønsker dette, billettpris: 199,-
```

```python
>>>billettpris(15, 'N', 'militær')

Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er militær - billettpris: 330,-
```

```python
>>>billettpris(10, 'N', 'barn')

Du kan ikke få minipris. Du får rabatt grunnet at du er barn - billettpris: 220,-
```

In [10]:
def bilettpris(tall, valg, situasjon):
    if tall == 15 and valg == "J":
        return print("Du kan få minipris: 199,-")
    elif tall == 10:
        return print("Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-")
    elif tall == 15 and valg == "N" and situasjon == "militær":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er militær - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "student":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er student - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "senior":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er senior - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "barn":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er barn - billettpris: 220,-")
    elif tall == 15 and valg == "N":
         return print("Du kan få minipris, men ønsker ikke det. Da tilbyr vi fullpris: 440,-")
    
bilettpris(10, "J", "militær")
bilettpris(15, "J", "militær")
bilettpris(15, "N", "militær")
bilettpris(15, "N", "student")
bilettpris(15, "N", "senior")
bilettpris(15, "N", "barn")

    

Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-
Du kan få minipris: 199,-
Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er militær - billettpris: 330,-
Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er student - billettpris: 330,-
Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er senior - billettpris: 330,-
Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er barn - billettpris: 220,-


## Oppgave d: frivillig

Du får godkjent oppgaven om du bare har klart a, b og delvis c, men prøv gjerne på denne litt vanskeligere d også.

Etter lobbyvirksomhet fra studentorganisasjoner endres reglene på følgende måte: Studenter får også litt rabatt på miniprisbilletter (10%),  samt at personer som både er studenter og militære  / 60+, eller studenter og barn, får to rabatter, og dermed bare betaler 0,75 * 0,75 eller 0.75 * 0.5 av fullpris. Merk at personer som er 60+ og militære, men ikke studenter, eller barn og militære, men ikke studenter, ikke får noen slik multiplisert rabatt, de må fortsatt nøye seg med den ene rabatten de hadde før, og de vanlige 199 for minipris. Endre funksjonen så den fungerer korrekt gitt de nye reglene.

In [ ]:
def bilettpris(tall, valg, situasjon):
    if tall == 10:
        return print("Minipris ikke lenger tilgjengelig, du må betale fullpris: 440,-")
    elif tall == 15 and valg == "N" and situasjon == "militær":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er militær - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "student":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er student - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "senior":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er senior - billettpris: 330,-")
    elif tall == 15 and valg == "N" and situasjon == "barn":
        return print("Du kan få minipris, men ønsker ikke det. Du får rabatt grunnet at du er barn - billettpris: 220,-")
    elif tall == 15 and valg == "N":
         return print("Du kan få minipris, men ønsker ikke det. Da tilbyr vi fullpris: 440,-")
    elif tall == 15 and valg == "J" and situasjon == "student":
        return print("Du kan få minipris med studentrabatt: 179,-")
    elif tall == 15 and valg == "J":
        return print("Du kan få minipris: 199,-")